#!/bin/bash

echo "This script assumes you git cloned the dotfiles repository to ~/dotfiles"

ln -s ~/dotfiles/config/mc ~/.config/mc
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/vim ~/.vim
ln -s ~/dotfiles/vimrc ~/.vimrc

echo "Symlinks are made"
